### PR TITLE
Stop defining `DISASMO` and define `BuildingInsideDisasmo=true` MSBuild property instead.

### LINKED ISSUE #52: Disasmo overrides project's `DefineConstants`
Since the `dotnet build` cmdline now includes `/p:DefineConstants=DISASMO`, this value is taken instead of any value defined in the csproj.

I like being able to detect Disasmo runs from my project and/or code, but maybe an alternate property would be better.  We could then bridge that into `DefineConstants` ourselves if we want that.

### PR DESCRIPTION
**Pull request by teo-tsirpanis**
Fixes #52.

### CODE REVIEW

**Comment by teo-tsirpanis** [comment]
@EgorBo can you please review?

**Comment by EgorBo** [comment]
@teo-tsirpanis oops, sorry for the delayed response, I decided to still define DISASMO symbol, but via .props

**Comment by teo-tsirpanis** [comment]
Thanks!

**Comment by EgorBo** [comment]
https://github.com/EgorBo/Disasmo/commit/2649e96733a29b7e9cbec2799e4ec66807971ade

**Pull request closed without merging**
